---
abstract: 'Tools to make migrating your DBIx::Class databases easier'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  File::Path: '2.09'
  File::Spec::Functions: '0'
  Test::Most: '0.34'
  Test::Requires: '0.08'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.032, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Class-Migration
no_index:
  directory:
    - examples
requires:
  Class::Load: '0.22'
  Config::MySQL: '0.02'
  DBD::SQLite: '1.46'
  DBIx::Class::DeploymentHandler: '0.002215'
  DBIx::Class::Fixtures: '1.001028'
  DBIx::Class::Schema::Loader: '0.07042'
  Devel::PartialDump: '0.17'
  File::Copy: '2.30'
  File::Path: '2.09'
  File::ShareDir::ProjectDistDir: '1.000004'
  File::Spec: '0'
  File::Temp: '0.2304'
  JSON::XS: '3.01'
  Moose: '2.1403'
  MooseX::Attribute::ENV: '0.02'
  MooseX::Getopt: '0.68'
  MooseX::Traits::Pluggable: '0.12'
  MooseX::Types: '0.45'
  MooseX::Types::LoadableClass: '0.013'
  Pod::Parser: '1.63'
  SQL::Translator: '0.11021'
  Text::Brew: '0.02'
  version: '0.9912'
resources:
  bugtracker: https://github.com/jjn1056/DBIx-Class-Migration/issues
  homepage: https://github.com/jjn1056/DBIx-Class-Migration
  repository: https://github.com/jjn1056/DBIx-Class-Migration.git
version: '0.056'
