---
abstract: 'Tools to make migrating your DBIx::Class databases easier'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  File::Path: '0'
  File::Spec::Functions: '0'
  Test::Most: '0'
  Test::Requires: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Class-Migration
no_index:
  directory:
    - examples
requires:
  Class::Load: '0'
  Config::MySQL: '0.02'
  DBD::SQLite: '1.35'
  DBIx::Class::DeploymentHandler: '0.002100'
  DBIx::Class::Fixtures: '1.001016'
  DBIx::Class::Schema::Loader: '0.07017'
  Devel::PartialDump: '0'
  File::Copy: '0'
  File::Path: '0'
  File::ShareDir::ProjectDistDir: '0.003001'
  File::Spec: '0'
  File::Temp: '0'
  JSON::XS: '2.32'
  Moose: '0'
  MooseX::Attribute::ENV: '0.02'
  MooseX::Getopt: '0.45'
  MooseX::Traits::Pluggable: '0'
  MooseX::Types: '0'
  MooseX::Types::LoadableClass: '0'
  Pod::Parser: '1.51'
  SQL::Translator: '0.11010'
  Text::Brew: '0'
  version: '0.77'
resources:
  bugtracker: https://github.com/jjn1056/DBIx-Class-Migration/issues
  homepage: https://github.com/jjn1056/DBIx-Class-Migration
  repository: https://github.com/jjn1056/DBIx-Class-Migration.git
version: '0.048'
x_contributors:
  - 'Alan Berndt <alan@eatabrick.org>'
  - 'Andy Gorman <andy@apacesystems.com>'
  - 'Andy Jones <andy@broadbean.com>'
  - 'Breno G. de Oliveira <garu@cpan.org>'
  - 'Brian Wightman <MidLifeXis@wightmanfam.org>'
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
  - 'chromatic <chromatic@wgz.org>'
  - 'Fitz Elliott <felliott@virginia.edu>'
  - 'jjn1056 <jjn1056@yahoo.com>'
  - 'John Napiorkowski <jjn1056@yahoo.com>'
  - 'Logan <loganbell@gmail.com>'
  - 'Matthias Krull <mkrull@uninets.eu>'
  - 'moltar <moltar@moltar.net>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Panu Ervamaa <panu.ervamaa@frantic.com>'
  - 'Paul Johnson <paul@pjcj.net>'
  - 'Samuel Kaufman <samuel.c.kaufman@gmail.com>'
  - 'Samuel Kaufman <skaufman@cpan.org>'
  - 'skaufman <sam@socialflow.com>'
  - 'Volker Kroll <kroll@strato-rz.de>'
  - 'Volker Kroll (vkroll) <kroll@strato-rz.de>'
